FROM miaortizma/jupyter:cull-base-cpu-ubuntu18.04

# Install Pytorch

RUN pip install \
    'torch' \
    'torch-vision' \
    'nltk' \
    'opencv-python' && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER  

