FROM miaortizma/jupyter:cull-base-cpu-ubuntu18.04

RUN pip install \
    'tensorflow==2.0.0-beta1' \
    'opencv-python' \
    'nltk' && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
    
