FROM miaortizma/jupyter:base-gpu

RUN pip install \
    'tensorflow-gpu==2.0.0-rc0' \
    'opencv-python' \
    'nltk' && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
    
